### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by bubnenkoff** [Mihail-K/vibrant.d#1]
Hello, could you add in readme comparison of classical vibed routing with Vibrant routing system? 

Also I have got question:

``` d
shared static this()
{
    with(Vibrant)
    {
        Get("/hello", (req, res) => "Hello user!");
```

Analog of:

``` d
shared static this()
{
    Vibrant.Get("/hello", (req, res) => "Hello user!");
```

**Comment by mintyfresh** [comment]
Aye, I'll add a comparison in the README. One was originally present, but I removed it because it was fairly long on vibe.d's side of things.

Also, yes. Those are equivalent, as is something like,

``` d
shared static this()
{
    auto router = Vibrant;

    router.Get("/hello", (req, res) => "Hello user!");
}
```

**Comment by bubnenkoff** [comment]
thanks, but how to specify port number?

2015-07-05 19:07 GMT+03:00 Mihail K notifications@github.com:

**Comment by mintyfresh** [comment]
You can specify a port in two ways. The short way is to supply it as a parameter,

``` d
with(Vibrant(8080))
{
}
```

However, you can also pass in an HTTPServerSettings object, if you so choose.

``` d
auto settings = new HTTPServerSettings;
settings.port = 8080;

with(Vibrant(settings))
{
}
```
